// If you modify this array, also update default language / dialect below.
const langs = [
  ['en-US', 'English(US)'],
  ['af-ZA', 'Afrikaans'],
  ['id-ID', 'Bahasa Indonesia'],
  ['ms-MY', 'Bahasa Melayu'],
  ['ca-ES', 'Català'],
  ['cs-CZ', 'Čeština'],
  ['da-DK', 'Dansk'],
  ['de-DE', 'Deutsch'],
  ['en-AU', 'English (Australia)'],
  ['en-CA', 'English (Canada)'],
  ['en-IN', 'English (India)'],
  ['en-NZ', 'English (New Zealand)'],
  ['en-ZA', 'English (South Africa)'],
  ['en-GB', 'English (UK)'],
  ['en-US', 'English (US)'],
  ['es-AR', 'Español (Argentina)'],
  ['es-BO', 'Español (Bolivia)'],
  ['es-CL', 'Español (Chile)'],
  ['es-CO', 'Español (Colombia)'],
  ['es-CR', 'Español (Costa Rica)'],
  ['es-EC', 'Español (Ecuador)'],
  ['es-SV', 'Español (El Salvador)'],
  ['es-ES', 'Español (España)'],
  ['es-US', 'Español (Estados Unidos)'],
  ['es-GT', 'Español (Guatemala)'],
  ['es-HN', 'Español (Honduras)'],
  ['es-MX', 'Español (México)'],
  ['es-NI', 'Español (Nicaragua)'],
  ['es-PA', 'Español (Panamá)'],
  ['es-PY', 'Español (Paraguay)'],
  ['es-PE', 'Español (Perú)'],
  ['es-PR', 'Español (Puerto Rico)'],
  ['es-DO', 'Español (República Dominicana)'],
  ['es-UY', 'Español (Uruguay)'],
  ['es-VE', 'Español (Venezuela)'],
  ['eu-ES', 'Euskara'],
  ['fil-PH', 'Filipino'],
  ['fr-FR', 'Français'],
  ['gl-ES', 'Galego'],
  ['hr-HR', 'Hrvatski'],
  ['zu-ZA', 'IsiZulu'],
  ['is-IS', 'Íslenska'],
  ['it-IT', 'Italiano'],
  ['it-IT', 'Italiano (Italia)'],
  ['it-CH', 'Italiano (Svizzera)'],
  ['lt-LT', 'Lietuvių'],
  ['hu-HU', 'Magyar'],
  ['nl-NL', 'Nederlands'],
  ['nb-NO', 'Norsk bokmål'],
  ['pl-PL', 'Polski'],
  ['pt-BR', 'Português (Brasil)'],
  ['pt-PT', 'Português (Portugal)'],
  ['ro-RO', 'Română'],
  ['sl-SL', 'Slovenščina'],
  ['sk-SK', 'Slovenčina'],
  ['fi-FI', 'Suomi'],
  ['sv-SE', 'Svenska'],
  ['vi-VN', 'Tiếng Việt'],
  ['tr-TR', 'Türkçe'],
  ['el-GR', 'Ελληνικά'],
  ['bg-BG', 'български'],
  ['ru-RU', 'Pусский'],
  ['sr-RS', 'Српски'],
  ['uk-UA', 'Українська'],
  ['ko-KR', '한국어'],
  ['cmn-Hans-CN', '中文 - 普通话 (中国大陆)'],
  ['cmn-Hans-HK', '中文 - 普通话 (香港)'],
  ['cmn-Hant-TW', '中文 - 中文 (台灣)'],
  ['yue-Hant-HK', '中文 - 粵語 (香港)'],
  ['ja-JP', '日本語'],
  ['hi-IN-JP', 'हिन्दी'],
  ['th-TH', 'ภาษาไทย']
]

export const availableLangues = langs.map(([value, label]) => {
  return {
    value,
    label
  }
})
